workflows:
  ios-workflow:
    name: Unity iOS Personal Build
    instance_type: mac_mini_m2
    environment:
      unity: "2022.3.62f2"        # Unity LTS version
      groups:
        - cluverse
      vars:
        BUNDLE_ID: com.kyrychenko.cluverse
        DEVELOPMENT_TEAM_ID: N3TZR6KJCB
        XCODE_WORKSPACE: ios/Unity-iPhone.xcworkspace
        XCODE_SCHEME: Unity-iPhone
      cocoapods: default

    scripts:

      - name: Activate Unity license
        script: |
          echo "$UNITY_LICENSE" > unity.ulf
          /Applications/Unity/Hub/Editor/$UNITY_VERSION/Unity.app/Contents/MacOS/Unity \
            -batchmode \
            -nographics \
            -manualLicenseFile unity.ulf \
            -quit
          echo "Unity activation finished"

      - name: Generate Xcode project with Unity
        script: |
          echo "Exporting Xcode project..."
          $UNITY_HOME/Contents/MacOS/Unity -batchmode -quit \
            -projectPath "$CM_BUILD_DIR" \
            -executeMethod BuildScript.BuildiOS \
            -logFile "$CM_BUILD_DIR/unity_build.log" \
            -nographics
          cat "$CM_BUILD_DIR/unity_build.log"

      - name: Build IPA for TestFlight / App Store
        script: |
          echo "Building IPA..."
          echo "UNITY_IOS_DIR='$UNITY_IOS_DIR'"
          ls -la "$UNITY_IOS_DIR"
          cd "$CM_BUILD_DIR"
          xcode-project build-ipa \
            --project "$UNITY_IOS_DIR/Unity-iPhone.xcodeproj" \
            --scheme "$XCODE_SCHEME" \
            --export-options-plist "$CM_BUILD_DIR/ExportOptions.plist"
          echo "IPA build complete"

    artifacts:
      - build/ipa/*.ipa
      - build/UnityApp.xcarchive
