workflows:
  ios-unity-appstore:
    name: Unity iOS App Store
    max_build_duration: 120
    instance_type: mac_mini_m1

    environment:
      groups:
        - cluverse   #all settings
      vars:
        UNITY_VERSION: 2022.3.62f2
        XCODE_WORKSPACE: "ios/Unity-iPhone.xcworkspace"
        XCODE_SCHEME: "Unity-iPhone"
        BUNDLE_ID: "com.kyrychenko.cluverse"
      xcode: latest
      cocoapods: default

    scripts:
      # Activate Unity
      - name: Activate Unity license
        script: |
          unity-editor \
            -batchmode \
            -nographics \
            -quit \
            -username "$UNITY_EMAIL" \
            -password "$UNITY_PASSWORD"

      # Build iOS project from Unity
      - name: Build Unity iOS project
        script: |
          unity-editor \
            -batchmode \
            -nographics \
            -quit \
            -projectPath . \
            -executeMethod BuildScript.BuildiOS

      # Install pods (Unity IAP, Ads, etc)
      - name: Install CocoaPods
        script: |
          cd ios
          pod install

      # Build and sign IPA
      - name: Build IPA
        script: |
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath build/UnityApp.xcarchive \
            archive \
            DEVELOPMENT_TEAM=$DEVELOPMENT_TEAM_ID \
            PRODUCT_BUNDLE_IDENTIFIER=$BUNDLE_ID

          xcodebuild \
            -exportArchive \
            -archivePath build/UnityApp.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build/ipa

    artifacts:
      - build/ipa/*.ipa
      - build/UnityApp.xcarchive
      - ios/build/**
