workflows:
  ios-workflow:
    name: Unity iOS Personal Build
    instance_type: mac_mini_m2
    environment:
      unity: "2022.3.62f2"        # Unity LTS version
      vars:
        UNITY_EMAIL: anton.kyrychenko11@gmail.com
        UNITY_PASSWORD: YBHo5z0D*&**AHMg
        BUNDLE_ID: com.kyrychenko.cluverse
        DEVELOPMENT_TEAM_ID: N3TZR6KJCB
        XCODE_WORKSPACE: ios/Unity-iPhone.xcworkspace
        XCODE_SCHEME: Unity-iPhone
      cocoapods: default

    scripts:

      - name: Activate Unity Personal
        script: |
          echo "Activating Unity Personal..."
          $UNITY_HOME/Contents/MacOS/Unity -batchmode -quit \
            -username "$UNITY_EMAIL" \
            -password "$UNITY_PASSWORD" \
            -serial "" \
            -logFile "$CM_BUILD_DIR/unity_activation.log"
          echo "Unity activated"

      - name: Generate Xcode project with Unity
        script: |
          echo "Exporting Xcode project..."
          $UNITY_HOME/Contents/MacOS/Unity -batchmode -quit \
            -projectPath "$CM_BUILD_DIR" \
            -executeMethod BuildScript.BuildIos \
            -logFile "$CM_BUILD_DIR/unity_build.log" \
            -nographics
          echo "Xcode project generated"

      - name: Build .ipa for TestFlight / App Store
        script: |
          xcodebuild \
            -project ios/Unity-iPhone.xcodeproj \
            -scheme Unity-iPhone \
            -configuration Release \
            -archivePath build/UnityApp.xcarchive \
            DEVELOPMENT_TEAM=$DEVELOPMENT_TEAM_ID \
            PRODUCT_BUNDLE_IDENTIFIER=$BUNDLE_ID

          xcodebuild \
            -exportArchive \
            -archivePath build/UnityApp.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build/ipa

    artifacts:
      - build/ipa/*.ipa
      - build/UnityApp.xcarchive
