workflows:
  ios-workflow:
    name: Unity iOS Personal Build
    instance_type: mac_mini_m2
    environment:
      unity: "2022.3.62f2"
      vars:
        BUNDLE_ID: com.kyrychenko.cluverse
    scripts:
      - name: Generate Xcode project with Unity
        script: |
          echo "Building Unity Xcode project..."
          unity -batchmode -quit \
            -projectPath . \
            -executeMethod BuildScript.BuildIos \
            -logFile ./unity_build.log \
            -nographics

      - name: Build .ipa for TestFlight
        script: |
          echo "Building .ipa..."
          xcode-project build-ipa \
            --project ios/Unity-iPhone.xcodeproj \
            --scheme Unity-iPhone

    artifacts:
      - build/ios/ipa/*.ipa
