workflows:
  ios-workflow:
    name: Unity iOS Personal Build
    instance_type: mac_mini_m2
    environment:
      vars:
        BUNDLE_ID: com.sashagames.blastblock
    scripts:
      - name: Build Xcode Project
        script: |
          unity -batchmode -quit \
            -projectPath . \
            -executeMethod BuildScript.BuildIos \
            -logFile -nographics
      - name: Build .ipa for TestFlight
        script: |
          xcode-project build-ipa --project ios/Unity-iPhone.xcodeproj --scheme Unity-iPhone
    artifacts:
      - build/ios/ipa/*.ipa